# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2e7f6e17ccd04b8266b40ebf2801a3dcddbb15c3f41ded69d7ad5b8b470d39adec2b428c5412ce2a93363f91fc384c64906f952b954bdefae17dd5c5eed7e0b2

test:
  secret_key_base: ccc773fb36d5a868c2a5061ae7cf85a475fceef7a3cacbfdbf2fb32201f23555d07adda6574458d315de981abced75a0aec8e3cff4b98ab6ab80e5f9a878efd4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
